# Site
# name: "Project ZZOM"
name: "프로젝트 ZZOM"
# title: "Project ZZOM"
title: "프로젝트 ZZOM"
# description: "One-person Publishing Project"
description: "읽어 보니 좋았던 책을 함께 볼 수 있게 번역합니다"
logo: 'assets/images/zzom-logo-dark (48 x 48).png'
favicon: 'favicon.ico'
baseurl: 
google_analytics: 'G-FL5818NYCK'
# mail-list: 
  # mailchimp: 'https://gmail.us2.list-manage.com/subscribe/post?u=f0c2c860abc78e38661cc5458&amp;id=fa3043bfc8'
  # stibee: 'https://stibee.com/api/v1.0/lists/3-GRmsmbil90tLfypP8ED7r_XfRLNA==/public/subscribers'
include: ["_pages"]
permalink: /:title/
image: assets/images/zzom-banner.jpg
locale: ko_KR

# Authors
authors:
  admin:
    name: admin
    display_name: ZZOM
    avatar: 'assets/images/zzom-logo-dark (200 x 200).png'
    email: project.zzom@gmail.com
    web: https://zzom.io
    twitter: https://twitter.com/project_zzom
    description: "공식 정보를 공유합니다."
  bomber:
    name: Shin Sang-jae
    display_name: 번역하는 개발자   
    avatar: 'assets/images/avatar-bomber.jpg'
    email: codelabor@gmail.com
    web: https://litt.ly/codelabor
    twitter: https://twitter.com/codelabor
    description: "개발하기 싫을 땐 번역합니다"  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 15
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-5050141342916334"
#adsense-data-ad-slot-vertical: "9543862036"
#adsense-data-ad-slot-horizontal: "2009821092"
#adsense-data-ad-slot-square: "1542083085"

# Facebook
facebook:
  enabled: false
  appId: "160845975895412"
  nounce: "2WuYKKrb"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
